import About from "@/components/About";
import Contact from "@/components/Contact";
import FAQ from "@/components/FAQ";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Terminal from "@/components/Terminal";
import Head from "next/head";

const Home = () => {
  return (
    <>
      <Head>
        <title>Kelompok Studi Linux UAJY</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
        <link href="https://fonts.googleapis.com" rel="preconnect" />
      </Head>
      <div className="bg-gradient-to-r from-[#03151B] to-[#1D1903]">
        <Navbar />
        <Terminal />
        <FAQ />
        <About />
        <Contact />
        <Footer />
      </div>
    </>
  );
};

export default Home;
